# Generated by Django 5.0.1 on 2024-02-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('authors', models.CharField(max_length=200)),
                ('adviser', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('astract', models.TextField()),
            ],
        ),
    ]
